# Generated by Django 5.0.3 on 2024-03-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_user_details_user_lname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_details',
            table='user_details',
        ),
    ]
